# Generated by Django 4.1.7 on 2023-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
    ]
